name              "npm"
maintainer        "Izzia Raffaele"
maintainer_email  "info@izziaraffaele.com"
license           "MIT"
description       "Installs or Updates PHP Project dependencies using NPM"
version           "1.0.0"